festival_vina/protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout='column1';

	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

public function getToken($token)
	{
		$model=User::model()->findByAttributes(array('token'=>$token));
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}
        
        public function actionVerToken($token)
        {
            $model=$this->getToken($token);
            if(isset($_POST['user']))
            {
                if($model->token==$_POST['user']['token']){
                    $model->password=crypt($_POST['user']['password']);
                    $model->token=null;
                    $model->save();
                    Yii::app()->user->setFlash('ganti','<b>Contraseña cambiada correctamente! por favor Inicie sesión</b>');
                    $this->redirect('?r=site/login');
                    $this->refresh();
                }
            }
            $this->render('verifikasi',array(
			'model'=>$model,
		));
        }
        
        public function actionForgot()
	{
            $getEmail=$_POST['Lupa']['email'];
            $getModel= User::model()->findByAttributes(array('email'=>$getEmail));
            if(isset($_POST['Lupa']))
            {
                $getToken=rand(0, 99999);
                $getTime=date("H:i:s");
                $getModel->token=md5($getToken.$getTime);
                $namaPengirim="City Express";
                $emailadmin="info@city-ex.cl";
                $subjek="Reset Password";
                $setpesan="Para restablecer con éxito su contraseña haga click en el enlace<br/>
                    <a href='http://city-ex.cl/festival_vina/site/vertoken?token=".$getModel->token."'>Reset Password</a>";
                if($getModel->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($namaPengirim).'?=';
				$subject='=?UTF-8?B?'.base64_encode($subjek).'?=';
				$headers="From: $name <{$emailadmin}>\r\n".
					"Reply-To: {$emailadmin}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-type: text/html; charset=UTF-8";
				$getModel->save();
                                Yii::app()->user->setFlash('forgot','Se le ha enviado un mail para poder cambiar la contraseña');
				mail($getEmail,$subject,$setpesan,$headers);
				$this->refresh();
			}
                
            }
		$this->render('forgot');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
	    if($error=Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
	    		echo $error['message'];
	    	else
	        	$this->render('error', $error);
	    }
	}


	public function actionUpdategrid(){
	if(Yii::app()->user->isAdmin)
	$this->render('updategrid');
	else
	throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	
	}
	public function actionUpdategridtarifa(){
	if(Yii::app()->user->isAdmin)
	$this->render('updategridtarifa');
	else
	throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	
	}
	public function actionContar(){
	$this->render('contar');
	}

	public function actionBarcodeqr(){
	$this->render('BarcodeQR');
	}

	public function actionGuardarporteria(){
	$this->render('guardarporteria');
	}
		
	public function actionAsignarservicio(){
	$this->render('asignarservicio');
	}
	
	public function actionVerservicio(){
	$this->render('verservicio');
	}

	public function actionGetdriver(){
	$this->render('getdriver');
	}
	
	public function actionVermapa(){
	$this->render('vermapa');
	}
	
	public function actionFnum(){
	$this->render('fnum');
	}
	
	public function actionIndex()
	{	
		if(Yii::app()->user->isGuest){
				if (!defined('CRYPT_BLOWFISH')||!CRYPT_BLOWFISH)
			throw new CHttpException(500,"This application requires that PHP was compiled with Blowfish support for crypt().");

		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
		}
		else
		{
			
			$this->render('index');
			
		}
	}
	
	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$headers="From: {$model->email}\r\nReply-To: {$model->email}";
				mail(Yii::app()->params['adminEmail'],$model->subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		if (!defined('CRYPT_BLOWFISH')||!CRYPT_BLOWFISH)
			throw new CHttpException(500,"This application requires that PHP was compiled with Blowfish support for crypt().");

		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
	

		public function actionReporte()
		{
	//if(Yii::app()->user->isAdmin){
		$model=new Filtro();
		if(isset($_POST['Filtro']))
		{
			$model->attributes=$_POST['Filtro'];

				$dataProvider=new CActiveDataProvider('Filtro');
				
				$this->render('exportar',array(
				'model'=>$model,
				));
				//Yii::app()->user->setFlash('reporte','Tu nombre es '.$model->fecha);
				
		}
		$this->render('reporte',array('model'=>$model));
	//}
	//else
	//throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	}
	
		public function actionReporte2()
		{
	if((Yii::app()->user->isJefe) || (Yii::app()->user->isAdmin)){
		$model=new Filtro();
		if(isset($_POST['Filtro']))
		{
			$model->attributes=$_POST['Filtro'];
			$dataProvider=new CActiveDataProvider('Filtro');
				
		}
		$this->render('reporte2',array('model'=>$model));
	}
	else
	throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	}
	
	
	public function actionFiltrar()
		{
	if((Yii::app()->user->isJefe) || (Yii::app()->user->isAdmin)){
		$model=new Filtro();
		if(isset($_POST['Filtro']))
		{
			$model->attributes=$_POST['Filtro'];

				$dataProvider=new CActiveDataProvider('Filtro');
				
			//	$this->render('reporte2',array(
				//'model'=>$model,
				//));
				//Yii::app()->user->setFlash('reporte','Tu nombre es '.$model->fecha);
				
		}
		$this->render('filtrar',array('model'=>$model));
	}
	else
	throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	}	


	public function actionFiltrar_tarifa()
		{
	if((Yii::app()->user->isJefe) || (Yii::app()->user->isAdmin)){
		$model=new Filtro();
		if(isset($_POST['Filtro']))
		{
			$model->attributes=$_POST['Filtro'];

				$dataProvider=new CActiveDataProvider('Filtro');
				
			//	$this->render('reporte2',array(
				//'model'=>$model,
				//));
				//Yii::app()->user->setFlash('reporte','Tu nombre es '.$model->fecha);
				
		}
		$this->render('filtrar_tarifa',array('model'=>$model));
	}
	else
	throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	}	

	public function actionPlanilla_tarifa()
		{
	if((Yii::app()->user->isJefe) || (Yii::app()->user->isAdmin)){
		$model=new Filtro();
		if(isset($_POST['Filtro']))
		{
			$model->attributes=$_POST['Filtro'];

				$dataProvider=new CActiveDataProvider('Filtro');
				
			//	$this->render('reporte2',array(
				//'model'=>$model,
				//));
				//Yii::app()->user->setFlash('reporte','Tu nombre es '.$model->fecha);
				
		}
		$this->render('planilla_tarifa',array('model'=>$model));
	}
	else
	throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	}	


	public function actionExportar2(){
	if(Yii::app()->user->isAdmin){
	$this->render('exportar2');
		
	}else
	throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	}

	public function actionExportardebug(){
	if(Yii::app()->user->isAdmin){
	$this->render('exportar_debug');
		
	}else
	throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	}
	public function actionExportar_planilla(){
	if(Yii::app()->user->isAdmin){
	$model=new Filtro();
		if(isset($_POST['Filtro']))
		{
			$model->attributes=$_POST['Filtro'];
	$dataProvider=new CActiveDataProvider('Filtro');
		$this->render('exportar_planilla',array(
			'model'=>$model,
		));
		}
	}else
	throw new CHttpException(500,"Usted no tiene permisos para aceeder");
	}

	
	public function actionExportar(){
	if(Yii::app()->user->isAdmin){
	$model=new Filtro();
		if(isset($_POST['Filtro']))
		{
			$model->attributes=$_POST['Filtro'];
	$dataProvider=new CActiveDataProvider('Filtro');

festival_vina/protected/views/site/contar.php
<?
	$this->layout= false;
	
	$datos = array();

	
	$datos[0] = Yii::app()->db->createCommand('SELECT COUNT(*) FROM vin_servicio WHERE cobro = 0 OR cobro IS NULL')->queryScalar();
	$datos[1] = Yii::app()->db->createCommand('SELECT COUNT(*) FROM vin_servicio WHERE (nro_movil = 0 OR nro_movil IS NULL) AND (cobro = 0 OR cobro IS NULL) ')->queryScalar();
	$datos[2] = Yii::app()->db->createCommand('SELECT COUNT(*) FROM vin_servicio WHERE hora_ter IS NULL')->queryScalar();
	$datos[3] = Yii::app()->db->createCommand('SELECT COUNT(*) FROM vin_servicio WHERE cobro <> 0 AND cobro IS NOT NULL')->queryScalar();
	$datos[4] = Yii::app()->db->createCommand('SELECT COUNT(*) FROM vin_servicio')->queryScalar();
	
	json_encode($datos);
	
?>

festival_vina/protected/views/site/fnum.php
<?php

$this->layout = false;
	$num = intval($_POST['num']);
	$num2 = intval($_POST['num2']);
	$nf = number_format($num, 0, ',', '.');
	$nf2 = number_format($num2, 0, ',', '.');
	
	echo json_encode($nf.';'.$nf2);

?>

festival_vina/protected/views/site/forgot.php
<?php
$this->pageTitle=Yii::app()->name . ' - Restaurar Password';
$this->breadcrumbs=array(
	'Restaurar Password',
);
?>
<?php if(Yii::app()->user->hasFlash('forgot')): ?>

<div class="flash-success">
	<?php echo Yii::app()->user->getFlash('forgot'); ?>
</div>

<?php else: ?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'forgot-form',
        'enableClientValidation'=>true,
	'clientOptions'=>array(
		'validateOnSubmit'=>true,
	),
)); ?>

	<div class="row">
            Email : <input name="Lupa[email]" id="ContactForm_email" type="email">
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

<?php endif; ?>

festival_vina/protected/views/site/index-test.php
<?php
/**
 * This is the bootstrap file for test application.
 * This file should be removed when the application is deployed for production.
 */

// change the following paths if necessary
$yii=dirname(__FILE__).'/../../framework/yii.php';
//$config=dirname(__FILE__).'/protected/config/test.php';

// remove the following line when in production mode
// defined('YII_DEBUG') or define('YII_DEBUG',true);

require_once($yii);
//Yii::createWebApplication($config)->run();


 $data = array(
    1 => array ('Name', 'Surname'),
    array('Schwarz', 'Oliver'),
    array('Test', 'Peter')
);
Yii::import('application.extensions.phpexcel.JPhpExcel');
$xls = new JPhpExcel('UTF-8', false, 'My Test Sheet');
$xls->addArray($data);
$xls->generateXML('my-test');
?>

festival_vina/protected/views/site/index.php
<?php

// change the following paths if necessary
$yii=dirname(__FILE__).'/../../framework/yii.php';
$config=dirname(__FILE__).'/protected/config/main.php';

// remove the following line when in production mode
// defined('YII_DEBUG') or define('YII_DEBUG',true);

require_once($yii);
Yii::createWebApplication($config)->run();

festival_vina/protected/views/site/planilla_tarifa.php
 <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>

<?php
	
	$tv = array();
	$source = Yii::app()->db->createCommand('SELECT nombre FROM vin_tipovehiculo ORDER BY nombre')->queryAll();
	foreach($source as $s)
	array_push($tv, $s['nombre']);	
	
	$ts = array();
	$source = Yii::app()->db->createCommand('SELECT nombre FROM vin_tiposervicio ORDER BY nombre')->queryAll();
	foreach($source as $s)
	array_push($ts, $s['nombre']);	
?>	
<script>
	

	
	function quitar_segundos(stri){
	return stri.substr(0, 5);
	}
	
	
	function filtrado()
	{
	$("#dataTable").handsontable('destroy');
	//var query = $('#query').val();
	var tipovehiculo = $('#tipovehiculo').val();
	var tiposervicio = $('#tipo_servicio').val();
	var serv_disp= $('#serv_disp').val();
	var c_o_p= $('#c_o_p').val();
	var valor_unitario= $('#valor_unitario').val();

	var flagnoadmin = <?php echo '0'.!(Yii::app()->user->isSuperAdmin);?>;
	
	
	var sourcetv = <?php echo json_encode($tv);?>;
	var sourcets= <?php echo json_encode($ts);?>;
	
		
	$.ajax({
		  type: 'POST',
		  datatype: 'json',
		  	url: 'filtrar_tarifa', 
			data: 'tipovehiculo='+tipovehiculo+'&tiposervicio='+tiposervicio,
			success: function (data, status, xhr)
			{
			
			$('input[name=yt0]').val('Buscar');
			
			function negativeValueRenderer(instance, td, th, row, col, prop, value, cellProperties) {
				Handsontable.renderers.TextRenderer.apply(this, arguments);
				if (!value || value === '') {
					td.style.background = '#EEE';
					}
			}
  
    Handsontable.renderers.registerRenderer('negativeValueRenderer', negativeValueRenderer); //maps function to lookup string
	
		
		var yellowRenderer = function (instance, td, row, col, prop, value, cellProperties) {
		if((row >= 0) && (flagnoadmin == 1))
		cellProperties.readOnly = true;
		if(col >= 0){
		Handsontable.renderers.TextRenderer.apply(this, arguments);
		
		//td.style.backgroundColor = 'lightblue';

		//td.class = 'readOnly';
		
		td.id = row+"_"+col;
		}

		
		};


		var obj = JSON.parse(data);
			
			$('#dataTable').handsontable({
			data: obj,
			colHeaders: ['#', 'Tipo Vehiculo','Tipo Servicio','Valor Servicio','Valor Hora'],
			rowHeaders: true,
			columns: [
    {data: "id_tarifa", type: 'text',  readOnly: true, renderer: yellowRenderer},
    {data: "tipovehiculo", type: 'autocomplete', readOnly: true, source: sourcetv, renderer: yellowRenderer},
    {data: "tipo_servicio",  type: 'autocomplete', readOnly: true, source: sourcets, renderer: yellowRenderer},
	{data: "valor_servicio", type: 'text', renderer: yellowRenderer},
	{data: "valor_hora", type: 'text', renderer: yellowRenderer},
	    
  ],
  
  beforeChange: function (changes, source) {
	
				if (changes) {

				var campo = changes[0][1];
				var id_antiguo = changes[0][2];
				var valornuevo= changes[0][3];
				var id_servicio = document.getElementById(changes[0][0]+'_0').innerHTML;
				//var descr = document.getElementById(changes[0][0]+'_1').innerHTML;
				//var kmadd = document.getElementById(changes[0][0]+'_1').innerHTML;
				//var progr = document.getElementById(changes[0][0]+'_1').innerHTML;
				
				
					$.ajax({
					type: 'POST',
					datatype: 'json',
					url: 'updategridtarifa', 
					data: 'campo='+campo+'&valornuevo='+valornuevo+'&id_fact='+id_servicio,
					success: function (data, status, xhr)
						{
						$('input[name=yt0]').val('Actualizar');
						}
					});
				
			 }
			 
			 },
			});
			
			
			$('#dataTable').width('100%').height(800);
			
			}	  
	});
	}
	

	
</script>
<script src="<?php echo Yii::app()->theme->baseUrl; ?>/dist/jquery.handsontable.full.js"></script>
<link rel="stylesheet" media="screen" href="<?php echo Yii::app()->theme->baseUrl; ?>/dist/jquery.handsontable.full.css">

<?php

$this->breadcrumbs=array(
	'Servicios'=>array('index'),
	'Administrar',
);

Yii::app()->clientScript->registerScript('search', "


$(document).ready(function() {
	filtrado();
});
	
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});

$('.searchbtn').click(function(){
	$('.filtro').toggle();
	return false;
});

$('.search-form form').submit(function(){
	$('#servicio-grid').show();
	$('#servicio-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
      
	 

");
?>


<h1>Administrar Servicios</h1>
<?php 
	
	echo CHtml::link('Formulario Busqueda','#',array('class'=>'searchbtn')); ?>

<div class="wide form">


<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl('site/reporte2'),
	'enableAjaxValidation'=>false,
	
)); ?>

<table class='filtro'>
<tr>
<td>

<div class="row">
		<?php echo CHtml::label('Tipo Vehiculo','' ,  array('style' => 'display:inline')); ?>
		<?php echo  CHtml::dropDownList('tipovehiculo', 'tipovehiculo', CHtml::listData(tipovehiculo::model()->findAll(array('order'=>'nombre')), 'id_tipovehiculo','nombre'), array('empty'=>'Seleccionar..'  )); ?>
	</div>
</td>

<td>
<div class="row">
		<?php echo CHtml::label('Tipo Servicio','' ,  array('style' => 'display:inline')); ?>
		<?php echo  CHtml::dropDownList('tipo_servicio', 'tipo_servicio', CHtml::listData(tiposervicio::model()->findAll(array('order'=>'nombre')), 'id_tiposervicio','nombre'), array('empty'=>'Seleccionar..'  )); ?>
	</div>
</td>

<td>	
	<div class="row buttons">
		<?php //echo CHtml::submitButton('Buscar');
		echo CHtml::button('Buscar',array('onclick'=>'javascript:filtrado();'));
	 ?>
	</div>
</td>



<?php $this->endWidget(); ?>


</div><!-- search-form -->
</tr>
	</table>


</div>
<div id="dataTable" style="overflow: scroll;"></div>
<br><br>

festival_vina/protected/views/site/updategridtarifa.php
<?
	$this->layout= false;
		
		 
	if($_POST['campo'] == 'valor_servicio'){
		$sql2= "UPDATE vin_tarifa SET valor_servicio  = '".$_POST['valornuevo']."' WHERE id_tarifa = '".$_POST['id_fact']."'";
		$result = Yii::app()->db->createCommand($sql2)->execute();
		$c_p = array("ok");
	}
		if($_POST['campo'] == 'valor_hora'){
		$sql2= "UPDATE vin_tarifa SET valor_hora  = '".$_POST['valornuevo']."' WHERE id_tarifa = '".$_POST['id_fact']."'";
		$result = Yii::app()->db->createCommand($sql2)->execute();
		$c_p = array("ok");
	}
	else
		$c_p = "No se cambie el valor campo";
	echo json_encode($c_p);
	
?>

festival_vina/protected/views/site/verifikasi.php
<?php
$this->pageTitle=Yii::app()->name . ' - Restaurar Password';
$this->breadcrumbs=array(
	'Restaurar Password',
);
?>
<h2>Bienvenido <?php echo $model->username;?> </h2>
<div class="form">
<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'Ganti-form',
)); ?>

	<div class="row">
            Nuevo Password : <input name="user[password]" id="ContactForm_email" type="password">
            <input name="user[token]" id="ContactForm_email" type="hidden" value="<?php echo $model->token?>">
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Submit'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

festival_vina/protected/views/site/vermapa.php
<?php
$this->layout = false;
?>
<!DOCTYPE html>
<html>
  <head>
    <title>Place details</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <style>
      html, body, #map-canvas {
        height: 100%;
        margin: 0px;
        padding: 0px
      }
    </style>
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>
    <script>
function initialize() {
  var map = new google.maps.Map(document.getElementById('map-canvas'), {
    center: new google.maps.LatLng(-33.0245270, -71.5523400), //Hotel+marina%20del+rey,+Viña+del+Mar,
	//new google.maps.LatLng(-33.8665433, 151.1956316),
    zoom: 15
  });

  var request = {
    placeId: 'ChIJN1t_tDeuEmsRUsoyG83frY4'
  };

  var infowindow = new google.maps.InfoWindow();
  var service = new google.maps.places.PlacesService(map);

  service.getDetails(request, function(place, status) {
    if (status == google.maps.places.PlacesServiceStatus.OK) {
      var marker = new google.maps.Marker({
        map: map,
        position: place.geometry.location
      });
      google.maps.event.addListener(marker, 'click', function() {
        infowindow.setContent(place.name);
        infowindow.open(map, this);
      });
    }
  });
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>
  </head>
  <body>
    <div id="map-canvas"></div>
  </body>
</html>

festival_vina/protected/views/site/verservicio.php
<?php
header('Access-Control-Allow-Origin: *');

$this->layout = false;

$id = $_POST['id'];
echo '<div style="border-color: blue; border-width: 2px; border-style: double; border-radius: 10px; padding: 10px;">';
echo '<b>Centro de costo:</b> '.centrocosto::model()->findByPk(servicio::model()->findByPk($id)->centrocosto)->nombre.'<br>';
echo '<b>Tipo servicio:</b> '.tiposervicio::model()->findByPk(servicio::model()->findByPk($id)->tipo_servicio)->nombre.'<br>';
echo '<b>Tipo vehiculo:</b> '.tipovehiculo::model()->findByPk(servicio::model()->findByPk($id)->tipo_vehiculo)->nombre.'<br>';
echo '<b>Solicitante:</b> '.User::model()->findByPk(servicio::model()->findByPk($id)->id_user)->username.'<br>';
echo '<b>Hora inicio serv.:</b> '.servicio::model()->findByPk($id)->hora_ini.'<br>';
echo '<b>Hora termino serv.:</b> '.servicio::model()->findByPk($id)->hora_ter.'<br>';
echo '<b>Pasajero Principal:</b> '.servicio::model()->findByPk($id)->pasajero_principal.'<br>';
echo '<u><b>Conductor:</b> '.proveedor::model()->findByPk(servicio::model()->findByPk($id)->nro_movil)->nombre.'</u><br>';
echo '<a href="tel:+569'.proveedor::model()->findByPk(servicio::model()->findByPk($id)->nro_movil)->telefono.'">'.proveedor::model()->findByPk(servicio::model()->findByPk($id)->nro_movil)->telefono.'</a>';

echo '</div>';

?>