teleton/protected/models/serveliminado.php
<?php

/**
 * This is the model class for table "{{serveliminado}}".
 *
 * The followings are the available columns in table '{{serveliminado}}':
 * @property integer $id_eliminado
 * @property integer $id_servicio
 * @property integer $id_user
 * @property string $fecha
 * @property string $fecha_emision
 * @property string $hora_emision
 * @property string $hora_ini
 * @property string $hora_ter
 * @property string $lugar_presentacion
 * @property integer $pasajeros
 * @property string $pasajero_principal
 * @property integer $telefono
 * @property integer $celular
 * @property string $lugar_destino
 * @property string $vuelo_in
 * @property string $vuelo_out
 * @property string $referencias
 * @property integer $tipo_servicio
 * @property integer $tipo_vehiculo
 * @property integer $centrocosto
 * @property string $nro_movil
 * @property integer $empresa
 * @property integer $nro_vale
 * @property integer $id_eliminador
 * @property string $fecha_eliminacion
 * @property string $hora_eliminacion
 */
class serveliminado extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{serveliminado}}';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('id_servicio, id_user, fecha, fecha_emision, hora_emision, hora_ini, lugar_presentacion, pasajeros, pasajero_principal, lugar_destino, tipo_servicio, tipo_vehiculo, centrocosto, fecha_eliminacion, hora_eliminacion', 'required'),
			array('id_servicio, id_user, pasajeros, telefono, celular, tipo_servicio, tipo_vehiculo, centrocosto, empresa, nro_vale, id_eliminador, pool, cobro', 'numerical', 'integerOnly'=>true),
			array('lugar_presentacion, pasajero_principal, lugar_destino, vuelo_in, vuelo_out', 'length', 'max'=>255),
			array('nro_movil, pool, cobro', 'length', 'max'=>15),
			array('hora_ter, referencias', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id_eliminado, id_servicio, id_user, fecha, fecha_emision, hora_emision, hora_ini, hora_ter, lugar_presentacion, pasajeros, pasajero_principal, telefono, celular, lugar_destino, vuelo_in, vuelo_out, referencias, tipo_servicio, tipo_vehiculo, centrocosto, nro_movil, empresa, nro_vale, id_eliminador, fecha_eliminacion, hora_eliminacion', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
		'tipo_vehiculo' => array(self::BELONGS_TO, 'tipovehiculo', 'tipo_vehiculo'),
		'tipo_servicio' => array(self::BELONGS_TO, 'tiposervicio', 'tipo_servicio'),
		'id_user' => array(self::BELONGS_TO, 'user', 'id_user'),
		'id_eliminador' => array(self::BELONGS_TO, 'user', 'id_eliminador'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id_eliminado' => 'Id Eliminado',
			'id_servicio' => 'Id Servicio',
			'id_user' => 'Id User',
			'fecha' => 'Fecha',
			'fecha_emision' => 'Fecha Emision',
			'hora_emision' => 'Hora Emision',
			'hora_ini' => 'Hora Ini',
			'hora_ter' => 'Hora Ter',
			'lugar_presentacion' => 'Lugar Presentacion',
			'pasajeros' => 'Pasajeros',
			'pasajero_principal' => 'Pasajero Principal',
			'telefono' => 'Telefono',
			'celular' => 'Celular',
			'lugar_destino' => 'Lugar Destino',
			'vuelo_in' => 'Vuelo In',
			'vuelo_out' => 'Vuelo Out',
			'referencias' => 'Referencias',
			'tipo_servicio' => 'Tipo Servicio',
			'tipo_vehiculo' => 'Tipo Vehiculo',
			'centrocosto' => 'Centrocosto',
			'nro_movil' => 'Nro Movil',
			'empresa' => 'Empresa',
			'nro_vale' => 'Nro Vale',
			'id_eliminador' => 'Id Eliminador',
			'fecha_eliminacion' => 'Fecha Eliminacion',
			'hora_eliminacion' => 'Hora Eliminacion',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id_eliminado',$this->id_eliminado);

		$criteria->compare('id_servicio',$this->id_servicio);

		//$criteria->compare('id_user',$this->id_user);

		if($this->fecha)
		$criteria->compare('fecha',date('Y-m-d', strtotime($this->fecha)), true);
		if($this->fecha_emision)
		$criteria->compare('fecha_emision', date('Y-m-d', strtotime($this->fecha_emision)),true);

		$criteria->compare('hora_emision',$this->hora_emision,true);

		$criteria->compare('hora_ini',$this->hora_ini,true);

		$criteria->compare('hora_ter',$this->hora_ter,true);

		$criteria->compare('lugar_presentacion',$this->lugar_presentacion,true);

		$criteria->compare('pasajeros',$this->pasajeros);

		$criteria->compare('pasajero_principal',$this->pasajero_principal,true);

		$criteria->compare('telefono',$this->telefono);

		$criteria->compare('celular',$this->celular);

		$criteria->compare('lugar_destino',$this->lugar_destino,true);

		$criteria->compare('vuelo_in',$this->vuelo_in,true);

		$criteria->compare('vuelo_out',$this->vuelo_out,true);

		$criteria->compare('referencias',$this->referencias,true);

		//$criteria->compare('tipo_servicio',$this->tipo_servicio);

		//$criteria->compare('tipo_vehiculo',$this->tipo_vehiculo);

		$criteria->compare('centrocosto',$this->centrocosto);

		$criteria->compare('nro_movil',$this->nro_movil,true);

		$criteria->compare('empresa',$this->empresa);

		$criteria->compare('nro_vale',$this->nro_vale);

		//$criteria->compare('id_eliminador',$this->id_eliminador);

		$criteria->compare('fecha_eliminacion',$this->fecha_eliminacion,true);

		if($this->hora_eliminacion)
		$criteria->compare('hora_eliminacion',date('Y-m-d', strtotime($this->hora_eliminacion)), true);


		$criteria->with = array('tipo_vehiculo', 'tipo_servicio','id_user', 'id_eliminador');
		$criteria->addCondition( 'tipo_vehiculo.nombre LIKE "%'.$this->tipo_vehiculo.'%" AND tipo_servicio.nombre LIKE "%'.$this->tipo_servicio.'%" AND id_user.username LIKE "%'.$this->id_user.'%" AND id_eliminador.username LIKE "%'.$this->id_eliminador.'%"');
		
		
		return new CActiveDataProvider('serveliminado', array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * @return serveliminado the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

teleton/protected/controllers/ServeliminadoController.php
<?php

class ServeliminadoController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @var CActiveRecord the currently loaded data model instance.
	 */
	private $_model;

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				   'expression'=>'$user->isSuperAdmin',
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				   'expression'=>'$user->isSuperAdmin',
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete','restaurar'),
				   'expression'=>'$user->isSuperAdmin',
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}



	public function actionRestaurar()
	{
		$model=$this->loadModel();
		
		$max = Yii::app()->db->createCommand('SELECT MAX(id_servicio) FROM tlt_servicio')->queryScalar() +1;
		
		if(!$model->nro_movil)
			$model->nro_movil = 0;
			
		//insertar
		$sql = 'INSERT INTO tlt_servicio(id_servicio, id_user, centrocosto, fecha, fecha_emision, hora_emision, hora_ini, 
		hora_ter, lugar_presentacion, comuna1, pasajeros, pasajero_principal, telefono, celular, lugar_destino, 
		comuna2, vuelo_in, vuelo_out, referencias, tipo_servicio, tipo_vehiculo, nro_movil) VALUES ('.
		$max.', '.$model->id_user.', '.$model->centrocosto.', "'.$model->fecha.'", "'.$model->fecha_emision.'", "'.$model->hora_emision.'", "'.$model->hora_ini.'", "'.
		$model->hora_ter.'", "'.$model->lugar_presentacion.'", '.$model->comuna1.', '.$model->pasajeros.', "'.$model->pasajero_principal.'", '.$model->telefono.', '.$model->celular.', "'.$model->lugar_destino.'", '.
		$model->comuna2.', "'.$model->vuelo_in.'", "'.$model->vuelo_out.'", "'.$model->referencias.'", '.$model->tipo_servicio.', '.$model->tipo_vehiculo.', '.$model->nro_movil.')';
		
		Yii::app()->db->createCommand($sql)->execute();
		//eliminar
		
		$this->loadModel()->delete();
		if(!isset($_GET['ajax']))
			$this->redirect(array('admin'));

	}
	/**
	 * Displays a particular model.
	 */
	public function actionView()
	{
		$this->render('view',array(
			'model'=>$this->loadModel(),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new serveliminado;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['serveliminado']))
		{
			$model->attributes=$_POST['serveliminado'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_eliminado));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['serveliminado']))
		{
			$model->attributes=$_POST['serveliminado'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id_eliminado));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'index' page.
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest)
		{
			// we only allow deletion via POST request
			$this->loadModel()->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_GET['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400,'Invalid request. Please do not repeat this request again.');
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('serveliminado');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new serveliminado('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['serveliminado']))
			$model->attributes=$_GET['serveliminado'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 */
	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=serveliminado::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404,'The requested page does not exist.');
		}
		return $this->_model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='serveliminado-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

teleton/protected/views/serveliminado/_form.php
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'serveliminado-form',
	'enableAjaxValidation'=>false,
)); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'id_servicio'); ?>
		<?php echo $form->textField($model,'id_servicio'); ?>
		<?php echo $form->error($model,'id_servicio'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'id_user'); ?>
		<?php echo $form->textField($model,'id_user'); ?>
		<?php echo $form->error($model,'id_user'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'fecha'); ?>
		<?php echo $form->textField($model,'fecha'); ?>
		<?php echo $form->error($model,'fecha'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'fecha_emision'); ?>
		<?php echo $form->textField($model,'fecha_emision'); ?>
		<?php echo $form->error($model,'fecha_emision'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'hora_emision'); ?>
		<?php echo $form->textField($model,'hora_emision'); ?>
		<?php echo $form->error($model,'hora_emision'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'hora_ini'); ?>
		<?php echo $form->textField($model,'hora_ini'); ?>
		<?php echo $form->error($model,'hora_ini'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'hora_ter'); ?>
		<?php echo $form->textField($model,'hora_ter'); ?>
		<?php echo $form->error($model,'hora_ter'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lugar_presentacion'); ?>
		<?php echo $form->textField($model,'lugar_presentacion',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'lugar_presentacion'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'pasajeros'); ?>
		<?php echo $form->textField($model,'pasajeros'); ?>
		<?php echo $form->error($model,'pasajeros'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'pasajero_principal'); ?>
		<?php echo $form->textField($model,'pasajero_principal',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'pasajero_principal'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'telefono'); ?>
		<?php echo $form->textField($model,'telefono'); ?>
		<?php echo $form->error($model,'telefono'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'celular'); ?>
		<?php echo $form->textField($model,'celular'); ?>
		<?php echo $form->error($model,'celular'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'lugar_destino'); ?>
		<?php echo $form->textField($model,'lugar_destino',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'lugar_destino'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'vuelo_in'); ?>
		<?php echo $form->textField($model,'vuelo_in',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'vuelo_in'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'vuelo_out'); ?>
		<?php echo $form->textField($model,'vuelo_out',array('size'=>60,'maxlength'=>255)); ?>
		<?php echo $form->error($model,'vuelo_out'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'referencias'); ?>
		<?php echo $form->textArea($model,'referencias',array('rows'=>6, 'cols'=>50)); ?>
		<?php echo $form->error($model,'referencias'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'tipo_servicio'); ?>
		<?php echo $form->textField($model,'tipo_servicio'); ?>
		<?php echo $form->error($model,'tipo_servicio'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'tipo_vehiculo'); ?>
		<?php echo $form->textField($model,'tipo_vehiculo'); ?>
		<?php echo $form->error($model,'tipo_vehiculo'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'centrocosto'); ?>
		<?php echo $form->textField($model,'centrocosto'); ?>
		<?php echo $form->error($model,'centrocosto'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'nro_movil'); ?>
		<?php echo $form->textField($model,'nro_movil',array('size'=>15,'maxlength'=>15)); ?>
		<?php echo $form->error($model,'nro_movil'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'empresa'); ?>
		<?php echo $form->textField($model,'empresa'); ?>
		<?php echo $form->error($model,'empresa'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'nro_vale'); ?>
		<?php echo $form->textField($model,'nro_vale'); ?>
		<?php echo $form->error($model,'nro_vale'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'id_eliminador'); ?>
		<?php echo $form->textField($model,'id_eliminador'); ?>
		<?php echo $form->error($model,'id_eliminador'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'fecha_eliminacion'); ?>
		<?php echo $form->textField($model,'fecha_eliminacion'); ?>
		<?php echo $form->error($model,'fecha_eliminacion'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'hora_eliminacion'); ?>
		<?php echo $form->textField($model,'hora_eliminacion'); ?>
		<?php echo $form->error($model,'hora_eliminacion'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

teleton/protected/views/serveliminado/_search.php
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'action'=>Yii::app()->createUrl($this->route),
	'method'=>'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model,'id_servicio'); ?>
		<?php echo $form->textField($model,'id_servicio'); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'id_user', array('style' => 'display:inline'));  ?>
		<?php echo $form->dropDownList($model,'id_user',CHtml::listData(User::model()->findAll(array('order'=>'username')), 'id','username'), array('empty'=>'Seleccionar..', 'style' => 'display:inline')); ?>

		<?php echo $form->label($model,'fecha', array('style' => 'display:inline')); ?>
		<?php echo $form->dateField($model,'fecha', array('style' => 'display:inline')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'fecha_emision', array('style' => 'display:inline')); ?>
		<?php echo $form->dateField($model,'fecha_emision', array('style' => 'display:inline')); ?>
	
		<?php echo $form->label($model,'hora_emision', array('style' => 'display:inline')); ?>
		<?php echo $form->timeField($model,'hora_emision', array('style' => 'display:inline')); ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'hora_ini', array('style' => 'display:inline')); ?>
		<?php echo $form->timeField($model,'hora_ini', array('style' => 'display:inline')); ?>
	
		<?php echo $form->label($model,'hora_ter', array('style' => 'display:inline')); ?>
		<?php echo $form->timeField($model,'hora_ter', array('style' => 'display:inline')); ?>
	</div>


	<div class="row">
		<?php echo $form->label($model,'tipo_servicio', array('style' => 'display:inline')); ?>
		<?php echo $form->dropDownList($model,'tipo_servicio',CHtml::listData(tiposervicio::model()->findAll(array('order'=>'nombre')), 'id_tiposervicio','nombre'), array('empty'=>'Seleccionar..', 'style' => 'display:inline'));  ?>		

		<?php echo $form->label($model,'tipo_vehiculo', array('style' => 'display:inline')); ?>
		<?php echo $form->dropDownList($model,'tipo_vehiculo',CHtml::listData(tipovehiculo::model()->findAll(array('order'=>'nombre')), 'id_tipovehiculo','nombre'), array('empty'=>'Seleccionar..', 'style' => 'display:inline'));  ?>		
	</div>

	<div class="row">
		<?php echo $form->label($model,'centrocosto', array('style' => 'display:inline')); ?>
		<?php echo $form->dropDownList($model,'centrocosto',CHtml::listData(centrocosto::model()->findAll(array('order'=>'nombre')), 'id_centrocosto','nombre'), array('empty'=>'Seleccionar..', 'style' => 'display:inline')); ?>

		<?php echo $form->label($model,'id_eliminador', array('style' => 'display:inline')); ?>
		<?php echo $form->dropDownList($model,'id_eliminador',CHtml::listData(User::model()->findAll(array('order'=>'username')), 'id','username'), array('empty'=>'Seleccionar..', 'style' => 'display:inline'));  ?>
	</div>

	<div class="row">
		<?php echo $form->label($model,'fecha_eliminacion', array('style' => 'display:inline')); ?>
		<?php echo $form->dateField($model,'fecha_eliminacion', array('style' => 'display:inline')); ?>

		<?php echo $form->label($model,'hora_eliminacion', array('style' => 'display:inline')); ?>
		<?php echo $form->timeField($model,'hora_eliminacion', array('style' => 'display:inline')); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton('Buscar'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

teleton/protected/views/serveliminado/admin.php
<?php
$this->breadcrumbs=array(
	'Serveliminados'=>array('index'),
	'Administrar',
);

$this->menu=array(
	//array('label'=>'List serveliminado', 'url'=>array('index')),
	//array('label'=>'Create serveliminado', 'url'=>array('create')),
	array('style' =>'display:none'),
);

Yii::app()->clientScript->registerScript('search', "
$(function(){
$('div.span3').hide();

$('div.span9').css('width','95%');

});

$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$('#serveliminado-grid').yiiGridView('update', {
		data: $(this).serialize()
	});
	return false;
});
");

 function formatear_fecha($string){
	//AAAA-mm-dd
	$anho = substr($string , 0, 4); 
	$mes = substr($string , 5, 2); 
	$dia = substr($string , 8, 2); 
	
	return $dia.'-'.$mes.'-'.$anho;
	}
function quitar_segundos($string){
	return substr($string , 0, -3); 
	}

?>

<h1>Administrar Servicios Historicos</h1>

<?php $this->widget('zii.widgets.grid.CGridView', array(
	'id'=>'serveliminado-grid',
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		//'id_eliminado',
		'id_servicio',
		//'id_user',
		array(
			'name' => 'id_user',
			'value' => 'User::model()->findByPk($data->id_user)->username',
		),		
		array(
			'name' => 'fecha',
			'value' => 'formatear_fecha($data->fecha)',
		),		
		array(
			'name' => 'fecha_emision',
			'value' => 'formatear_fecha($data->fecha_emision)',
		),
		array(
			'name' => 'hora_emision',
			'value' => 'quitar_segundos($data->hora_emision)',
		),		
		array(
			'name' => 'hora_ini',
			'value' => 'quitar_segundos($data->hora_ini)',
		),		
		array(
			'name' => 'hora_ter',
			'value' => 'quitar_segundos($data->hora_ter)',
		),		

		array(
			'name' => 'tipo_servicio',
			'value' => 'tiposervicio::model()->findByPk($data->tipo_servicio)->nombre',
		),		
		array(
			'name' => 'tipo_vehiculo',
			'value' => 'tipovehiculo::model()->findByPk($data->tipo_vehiculo)->nombre',
		),		

		array(
			'name' => 'centrocosto',
			'value' => 'centrocosto::model()->findByPk($data->centrocosto)->nombre',
		),		
		
		array(
			'name' => 'id_eliminador',
			'value' => 'User::model()->findByPk($data->id_eliminador)->username',
		),		
		
		array(
			'name' => 'fecha_eliminacion',
			'value' => 'formatear_fecha($data->fecha_eliminacion)',
		),		
		array(
			'name' => 'hora_eliminacion',
			'value' => 'quitar_segundos($data->hora_eliminacion)',
		),				
		array(
			'class'=>'CButtonColumn',
			'template' =>'{restaurar} {delete}',
			'buttons'=>array
				(
				'restaurar' => array
				(
					'label'=>'restaurar',
					'imageUrl'=>Yii::app()->request->baseUrl.'/data/restore.png',
					'url'=>'Yii::app()->createUrl("serveliminado/restaurar", array("id"=>$data->id_eliminado))',
					
				),
				),
		),
	),
)); ?>